version: '3.9'

services:
  mongodb: 
    image: mongo:7.0.4
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=root123
    volumes:
      - mongodb-data:/data/db

volumes:
  mongodb-data: {}
